"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
def compute():
    prev, fut = 1, 2
    even = 0
    while prev <= 4000000:
        current = prev + fut
        if current % 2 == 0:  # check if is even valued
            even += current
        prev, fut = fut, current # swap values
    return even


if __name__ == "__main__":
    print(compute())
